# Generated by Django 4.1.3 on 2022-12-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_score_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
    ]
