# Generated by Django 4.1.3 on 2022-12-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_score_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='wrong',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
