# Generated by Django 4.1.3 on 2022-12-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_score_correct_alter_score_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
