# Generated by Django 4.1.3 on 2022-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_rename_create_time_score_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
