# Generated by Django 4.1.3 on 2022-12-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_rename_question_question_curr_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prev_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='quizzes.question'),
        ),
    ]
