# Generated by Django 4.1.3 on 2022-12-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_question_prev_question_alter_question_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prev_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='quizzes.question'),
        ),
    ]
