# Generated by Django 4.1.3 on 2022-12-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_question_next_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question'),
        ),
    ]
