# Generated by Django 4.1.3 on 2022-12-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_alter_quiz_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question'),
        ),
    ]
