# Generated by Django 4.1.3 on 2022-12-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_quiz_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prev_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='quizzes.question'),
        ),
    ]
